spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/m2s07
    username: postgres
    password: 8882
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true